name: Luv.n.Romance
favicon: null
layout_spectrum: 0.11694160290062428
typography_spectrum: 0.47217517136596143
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.22065734677016735
  lightness: 0.30678945081308484
  saturation: 0.2672241381369531
  rhythmicContrast: 0.9152209060266614
purpose: []
